### PR TITLE
Set of bit rate based on hamlib

### PR DESCRIPTION
**Pull request by iw2nke**
It solved my issue

### CODE REVIEW

**Comment by F4HTB** [comment]
Thanks for this submit.
It seems to me that in an old version I had implemented it as and then I went to:
self.serialport.rate = config ['HAMLIB'] ['rig_rate']
Thanks for confirming this.
Do not hesitate if you have some proposals.
73 F4HTB

**Comment by iw2nke** [comment]
Dear Olivier,
 I've expanded few features of your great software (PTT support for other
methods, setting of ATT and PREAMP, etc.)
Before to submit, could we discuss the way to growth functionalities? If it
helps, we can have a call.
73 de IW2NKE

Il Ven 8 Gen 2021, 00:48 Olivier SCHMITT <notifications@github.com> ha
scritto:

**Comment by F4HTB** [comment]
Hi Dear Iw2nke ,

Hope my email will reach you.
Thank you to confirm that you have received. Responding to emails 
through github sometimes loses responses apparently.

I would of course be happy to work on the project with other people like 
you.
Can you tell me more about your developments?

1.PTT
Why I didn't add PTT by dtr, rts or gpio is that it doesn't make sense 
to me to be able to allow it other than by CAT. Indeed, if you do not 
have the cat, impossible to adjust the reception frequency, so I did not 
see why to put it.
Maybe you have another vision? Are there any TRXs that allow CAT but the 
PTT option is not there?

2.Other functions specific to TRX
I had thought of adding the functions PREAMP, ATT, NB, etc ... But 
again, all the functions are not necessarily accessible on all TRX.
Here I had possibly planned to add a dynamic third page. This would be 
based on showing only the functions usable on the declared TRX.
It seems indeed that in the hamlib we can list what is accessible as 
well as the type and possible options.

So for the latter, I suggest you do as for the FI option via rtl-sdr, it 
is to create a third page which lists automatically according to the 
position.
What do you think?
It should not be forgotten that each of the activated or deactivated 
functions must be appear to the other users.
This is because UHRR is designed for use by multiple simultaneous users.

3.The functions directly in the software.
The other vision would also have been to put processing functions 
directly on the interface.
For example, it would be possible to add NB or other DSP processing 
directly to the audio stream.

4.CW functions
It seems to me that it might be wise to add functions for the CW to the 
keyboard.
Creating an interface for a manipulator should go through the 
communication of an interface. I imagine that the easiest way to do this 
would be via a serial port via an arduino or atony 85. Computers without 
a GPIO.
We must remain the most common.
So we should not dev something on a client in rapsberry pi via GPIO.If 
that was the case, there would be more efficient stream transmissions to do.
The CW on the keyboard therefore seems to me a good compromise so as not 
to deviate into a "problem factory".
Likewise, on a third page. We could therefore add the sending of the 
audio entered on the keyboard or the sending of the text and would be 
the python code which would generate the CW.
In another way, in reception, we could add an automatic decoding in 
javascript.
I had found some CW javascript decoding projects on the internet, but 
after asking the members of the radio club where I am for some tests, 
the tests were not conclusive.

5.Management of a rotor.
The other thing that I found interesting with hamlib is that it allows 
you to control rotors. There could also be a third page to control the 
rotors.
You should use an HTML5 canvas to display the azimuth and elevation and 
allow you to click where you want it to go.
You have to manage interruptions during movement if you want to change 
direction or stop, etc ... As well as the button to stay pressed for 
controlled movement.

6.Installation on other distribution
If you have the opportunity, there seems to be a demand to install the 
server on Ubuntu 20.4.
Maybe you would have time to make it a wiki page to help with this setup?

Conclusion:
There are still many opportunities to add functionality.
Breaking this up into several third-party pages like the FI seems to me 
better for slicing up and splitting up code and errors.
The user can access it by tabs of his browser or several screens of his 
installation.

Finally, I still make a point of respecting the "keep it simple". 
Indeed, the more you add things, the heavier the code will be with 
possible bugs.
You'll also notice that the more stuff, the more time you spend 
responding to issues, not about a bug but how to use your code and and 
why it doesn't work in slightly different configurations.
I wondered if it wasn't more coherent to wait for feature requests.

The main reason for UHRR was to do remote voice. Sometimes you have to 
wonder why we are doing things and if it is really necessary.

While waiting for your comments, I wish you a pleasant day.
Your interest thrills me.

73 F4HTB

PS: I am not very comfortable with speak in English. I often have to 
search for words, so an email exchange is fine for me.
Thank you for your discussion proposal.


Le 16/01/2021 à 09:47, iw2nke a écrit :

**Comment by iw2nke** [comment]
In line my answers.
73

Gian Leonardo [IW2NKE]

Il giorno sab 16 gen 2021 alle ore 13:38 Olivier SCHMITT <
notifications@github.com> ha scritto:

> Hi Dear Iw2nke ,
>
> Hope my email will reach you.
> Thank you to confirm that you have received. Responding to emails
> through github sometimes loses responses apparently.
>
> I would of course be happy to work on the project with other people like
> you.
> Can you tell me more about your developments?
>
> 1.PTT
> Why I didn't add PTT by dtr, rts or gpio is that it doesn't make sense
> to me to be able to allow it other than by CAT. Indeed, if you do not
> have the cat, impossible to adjust the reception frequency, so I did not
> see why to put it.
> Maybe you have another vision? Are there any TRXs that allow CAT but the
> PTT option is not there?
>

My TS-2000 is a key example. The CAT command to switch on/off the PTT is
useless, since the audio related to the command is the one coming from the
MIC socket.
To switch the audio coming through the ACC socket a PTT logic level must be
routed on the same connector.
Quite trivial, but I assume it is not a corner case and the option could be
simply included in the config process.


> 2.Other functions specific to TRX
> I had thought of adding the functions PREAMP, ATT, NB, etc ... But
> again, all the functions are not necessarily accessible on all TRX.
> Here I had possibly planned to add a dynamic third page. This would be
> based on showing only the functions usable on the declared TRX.
> It seems indeed that in the hamlib we can list what is accessible as
> well as the type and possible options.
>

It is exactly what I assume. You can populate a specific space of the
console with the supported functions.
Obviously this part must be the second step after the first configuration,
but a static record is necessary. A tedious check after each


> So for the latter, I suggest you do as for the FI option via rtl-sdr, it
> is to create a third page which lists automatically according to the
> position.
> What do you think?
> It should not be forgotten that each of the activated or deactivated
> functions must be appear to the other users.
> This is because UHRR is designed for use by multiple simultaneous users.
>
> 3.The functions directly in the software.
> The other vision would also have been to put processing functions
> directly on the interface.
> For example, it would be possible to add NB or other DSP processing
> directly to the audio stream.
>
> 4.CW functions
> It seems to me that it might be wise to add functions for the CW to the
> keyboard.
> Creating an interface for a manipulator should go through the
> communication of an interface. I imagine that the easiest way to do this
> would be via a serial port via an arduino or atony 85. Computers without
> a GPIO.
> We must remain the most common.
> So we should not dev something on a client in rapsberry pi via GPIO.If
> that was the case, there would be more efficient stream transmissions to
> do.
> The CW on the keyboard therefore seems to me a good compromise so as not
> to deviate into a "problem factory".
> Likewise, on a third page. We could therefore add the sending of the
> audio entered on the keyboard or the sending of the text and would be
> the python code which would generate the CW.
> In another way, in reception, we could add an automatic decoding in
> javascript.
> I had found some CW javascript decoding projects on the internet, but
> after asking the members of the radio club where I am for some tests,
> the tests were not conclusive.
>

I am not interested in the support of digital mode in this way. A lot of
others software can encode/decode and are easily accessible for remote
operations.


> 5.Management of a rotor.
> The other thing that I found interesting with hamlib is that it allows
> you to control rotors. There could also be a third page to control the
> rotors.
> You should use an HTML5 canvas to display the azimuth and elevation and
> allow you to click where you want it to go.
> You have to manage interruptions during movement if you want to change
> direction or stop, etc ... As well as the button to stay pressed for
> controlled movement.
>

Too complex for my skills...


> 6.Installation on other distribution
> If you have the opportunity, there seems to be a demand to install the
> server on Ubuntu 20.4.
> Maybe you would have time to make it a wiki page to help with this setup?
>

I am developing only under RPi, debian/raspbian/rasperry os. Ubuntu is out
of my space.

>
> Conclusion:
> There are still many opportunities to add functionality.
> Breaking this up into several third-party pages like the FI seems to me
> better for slicing up and splitting up code and errors.
> The user can access it by tabs of his browser or several screens of his
> installation.
>
> Finally, I still make a point of respecting the "keep it simple".
> Indeed, the more you add things, the heavier the code will be with
> possible bugs.
> You'll also notice that the more stuff, the more time you spend
> responding to issues, not about a bug but how to use your code and and
> why it doesn't work in slightly different configurations.
> I wondered if it wasn't more coherent to wait for feature requests.
>
> The main reason for UHRR was to do remote voice. Sometimes you have to
> wonder why we are doing things and if it is really necessary.
>

I am fully in line with you.
When ready I will share with you some enhancement.
73,
-- 
Gian Leonardo Solazzi

**Pull request merged**
